# Generated by Django 5.2.16 on 2026-10-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='Unique OPIS Truckstop ID', unique=True)),
                ('name', models.CharField(help_text='Truckstop Name', max_length=255)),
                ('address', models.CharField(blank=True, help_text='Physical address / highway exit', max_length=255)),
                ('city', models.CharField(db_index=True, help_text='City name', max_length=100)),
                ('state', models.CharField(db_index=True, help_text='Two-letter state / province code', max_length=10)),
                ('rack_id', models.IntegerField(blank=True, help_text='Rack identifier from source data', null=True)),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=4, help_text='Retail price per gallon (USD)', max_digits=7)),
                ('latitude', models.FloatField(db_index=True, help_text='Latitude coordinate (WGS84)')),
                ('longitude', models.FloatField(db_index=True, help_text='Longitude coordinate (WGS84)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fuel_stations',
                'ordering': ['retail_price'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='idx_station_coords'), models.Index(fields=['state', 'city'], name='idx_station_location'), models.Index(fields=['retail_price'], name='idx_station_price')],
            },
        ),
    ]
